// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjewtytmutxstitnimjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqZXd0eXRtdXR4c3RpdG5pbWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODA5ODksImV4cCI6MjA1NjQ1Njk4OX0.plol0vzk56AUrswuLDIhTQjH0_qxM7Nu5egFOZXrgY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);